# Generated by Django 2.1.2 on 2018-10-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campoPalabra', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
