# Generated by Django 2.1.2 on 2018-11-18 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prototipo', '0005_formulariofinal_depth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulariofinal',
            old_name='Word',
            new_name='PalabraABuscar',
        ),
        migrations.RenameField(
            model_name='formulariofinal',
            old_name='Depth',
            new_name='Profundidad',
        ),
    ]
