# Generated by Django 2.1.2 on 2019-03-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototipo', '0006_auto_20181118_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeiSpa30Relation',
            fields=[
                ('relation', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('sourcesynset', models.CharField(db_column='sourceSynset', max_length=17)),
                ('sourcepos', models.CharField(db_column='sourcePos', max_length=1)),
                ('targetsynset', models.CharField(db_column='targetSynset', max_length=17)),
                ('targetpos', models.CharField(db_column='targetPos', max_length=1)),
                ('csco', models.FloatField()),
                ('method', models.CharField(max_length=2)),
                ('version', models.CharField(max_length=1)),
                ('wnsource', models.CharField(db_column='wnSource', max_length=4)),
            ],
            options={
                'db_table': 'wei_spa-30_relation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeiSpa30Variant',
            fields=[
                ('word', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('sense', models.IntegerField()),
                ('offset', models.CharField(max_length=17)),
                ('pos', models.CharField(max_length=1)),
                ('csco', models.FloatField()),
                ('experiment', models.CharField(blank=True, max_length=20, null=True)),
                ('mark', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'wei_spa-30_variant',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Formulario',
        ),
        migrations.DeleteModel(
            name='FormularioFinal',
        ),
        migrations.DeleteModel(
            name='FormularioTerminos',
        ),
    ]
