# Generated by Django 2.1.2 on 2019-04-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototipo', '0008_weispa30synset'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeiSpa30Examples',
            fields=[
                ('offset', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('pos', models.CharField(max_length=1)),
                ('sense', models.IntegerField()),
                ('word', models.CharField(max_length=100)),
                ('examples', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wei_spa-30_examples',
                'managed': False,
            },
        ),
    ]
